Add controller tests
AKeeganDev/blog_app pull request #6
Opened 2022-07-13 22:17 UTC by AKeeganDev

This pull request features 3 tests for my user and posts controllers. The three tests each check

- That the index is rendered properly
- Placeholder text is properly rendered
- response code 200 is sent when calling the correct paths

2022-07-13 22:52 UTC, andersonlebon requested changes
## Hi @AKeeganDev 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 22:52 UTC, andersonlebon commented on spec/controllers/posts_controller_spec.rb
> +  end
- [ ] Kindly add a test for the user/show action. hint :point_down: 

```rb
expect(response).to render_template(:show)
```

2022-07-13 22:52 UTC, andersonlebon commented on spec/controllers/users_controller_spec.rb
> +  end
- [x] Kindly make sure the user/show action is tested. Hint :point_down: 
```rb
expect(response).to render_template(:show)
```

2022-07-14 18:07 UTC, DeliceLydia approved these changes
## Hi @AKeeganDev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 18:10 UTC, merged